function Hd = notch_60_bw_4
%NOTCH_60_BW_4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 26-Nov-2019 14:22:52

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Fnotch = 60;  % Notch Frequency
BW     = 4;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd = dsp.IIRFilter( ...
    'Structure', 'Direct form II', ...
    'Numerator', b, ...
    'Denominator', a);

% [EOF]
